apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stacklaunch-api.fullname" . }}
  labels:
    {{- include "stacklaunch-api.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "stacklaunch-api.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "stacklaunch-api.selectorLabels" . | nindent 8 }}

    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: {{ .Chart.Name }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}

          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP



          env:
            - name: APP_ENV
              value: {{ .Values.environment.name | quote }}

            - name: LOG_LEVEL
              value: {{ .Values.environment.logLevel | quote }}

            - name: DB_HOST
              value: {{ .Values.database.host | quote }}

            - name: DB_PORT
              value: {{ .Values.database.port | quote }}

            - name: DB_NAME
              value: {{ .Values.database.name | quote }}

            - name: DB_USER
              value: {{ .Values.database.user | quote }}

            - name: DB_SSLMODE
              value: {{ .Values.database.sslMode | quote }}

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.passwordKey }}

          {{- if .Values.temporaryStorage.enabled }}
          volumeMounts:
            - name: temporary-storage
              mountPath: {{ .Values.temporaryStorage.mountPath }}
          {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- if .Values.temporaryStorage.enabled }}
      volumes:
        - name: temporary-storage
          emptyDir:
            sizeLimit: {{ .Values.temporaryStorage.sizeLimit }}
      {{- end }}