apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  labels:
    {{- include "stacklaunch-api.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ required "database.password must be provided" .Values.database.password | b64enc | quote }}