apiVersion: v1
kind: Pod
metadata:
  name: secrets-manager-test
  namespace: dev
spec:
  serviceAccountName: go-api
  restartPolicy: Never

  containers:
    - name: aws-cli
      image: public.ecr.aws/aws-cli/aws-cli:latest
      command:
        - sh
        - -c
        - sleep 3600
