replicaCount: 1

image:
  repository: stacklaunch-go-api
  tag: v1
  pullPolicy: IfNotPresent

environment:
  name: development
  logLevel: debug

database:
  host: postgres.dev.svc.cluster.local
  name: stacklaunch_dev
  user: stacklaunch_dev
  password: dev-lab-password

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi