replicaCount: 1

image:
  repository: stacklaunch-go-api
  tag: v99909
  pullPolicy: IfNotPresent

environment:
  name: development
  logLevel: debug

database:
  host: db-stacklaunch.cxes4uuugay0.eu-west-1.rds.amazonaws.com
  port: "5432"
  name: postgres
  user: stacklaunchadmin
  sslMode: require

  # Existing Kubernetes Secret
  secretName: go-api-database-secret
  passwordKey: database-password

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: dev.api.stacklaunch.local
  path: /
  pathType: Prefix

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  privileged: false
  capabilities:
    drop:
      - ALL

temporaryStorage:
  enabled: true
  mountPath: /tmp
  sizeLimit: 100Mi